### ISSUE TITLE
Test test_underlying_decode_matchinfo fails on PPC64 and s390x on openSUSE

### ISSUE THREAD

**Issue by skriesch** [simonw/sqlite-fts4#6]
We have got failed builds at openSUSE for the architectures PPC64 and s390x.
The test test_underlying_decode_matchinfo has got the following information:

```
[   67s] =================================== FAILURES ===================================
[   67s] _ test_underlying_decode_matchinfo[\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00-expected0] _
[   67s] 
[   67s] buf = b'\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00'
[   67s] expected = (1, 2, 2, 2)
[   67s] 
[   67s]     @pytest.mark.parametrize(
[   67s]         "buf,expected",
[   67s]         [
[   67s]             (
[   67s]                 b"\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00",
[   67s]                 (1, 2, 2, 2),
[   67s]             )
[   67s]         ],
[   67s]     )
[   67s]     def test_underlying_decode_matchinfo(buf, expected):
[   67s] >       assert expected == decode_matchinfo(buf)
[   67s] E       assert (1, 2, 2, 2) == (16777216, 33...432, 33554432)
[   67s] E         At index 0 diff: 1 != 16777216
[   67s] E         Full diff:
[   67s] E         - (16777216, 33554432, 33554432, 33554432)
[   67s] E         + (1, 2, 2, 2)
[   67s] 
[   67s] tests/test_sqlite_fts4.py:67: AssertionError
```

**Comment by simonw** [comment]
Oh interesting!

Here's the function in question: https://github.com/simonw/sqlite-fts4/blob/c50c70f4fd561c9a675349c2d87e9e6c8676c469/sqlite_fts4/__init__.py#L33-L35

**Comment by simonw** [comment]
Some clues here: https://stackoverflow.com/questions/25570867/why-does-pythons-struct-think-little-endian-and-big-endian-imply-different-leng

It looks like `struct.unpack()` defaults to the host system's idea of big-endian vs little-endian, unlessy you use `>` or `<` syntax instead: https://docs.python.org/3/library/struct.html#struct-alignment

**Comment by simonw** [comment]
I think this is it. Here's a diff I applied:

```diff
diff --git a/sqlite_fts4/__init__.py b/sqlite_fts4/__init__.py
index 3a6af80..f193f91 100644
--- a/sqlite_fts4/__init__.py
+++ b/sqlite_fts4/__init__.py
@@ -32,7 +32,7 @@ def decode_matchinfo_str(buf):
 
 def decode_matchinfo(buf):
     # buf is a bytestring of unsigned integers, each 4 bytes long
-    return struct.unpack("I" * (len(buf) // 4), buf)
+    return struct.unpack(">" + ("I" * (len(buf) // 4)), buf)
 
 
 def _error(m):
```
This caused the tests to fail like so:
```
FAILED tests/test_sqlite_fts4.py::test_decode_matchinfo[dog-expected0] - assert [1, 2, 1, 1, 1, 2, 4, 2, 5, 4, 5, 5, 5] == [16777216,\n 33554432,\n 16777216,\n 16777216,\n...
FAILED tests/test_sqlite_fts4.py::test_decode_matchinfo[cat-expected1] - assert [1, 2, 1, 1, 1, 2, 3, 2, 5, 4, 5, 5, 5] == [16777216,\n 33554432,\n 16777216,\n 16777216,\n...
```
Using this instead keeps the tests passing:

```python
struct.unpack("<" + ("I" * (len(buf) // 4)), buf)
```

**Comment by simonw** [comment]
Confirming my system is little-endian:
```pycon
>>> from sys import byteorder
>>> byteorder
'little'
```

**Comment by simonw** [comment]
I just shipped 1.0.2 to PyPI which should fix this. I'll leave this issue open so you can confirm the fix works at your end!

**Comment by simonw** [comment]
Turned this into a TIL: https://til.simonwillison.net/python/struct-endianness

**Comment by skriesch** [comment]
Thank you very much for your effort! But it seems that we have got more failing tests for s390x and PPC64 now (other architectures not affected):
```
[   13s] ============================= test session starts ==============================
[   13s] platform linux -- Python 3.8.13, pytest-7.1.1, pluggy-1.0.0 -- /usr/bin/python3.8
[   13s] cachedir: .pytest_cache
[   13s] SQLite version: 3.39.2
[   13s] rootdir: /home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2
[   13s] collecting ... collected 10 items
[   13s] 
[   13s] tests/test_sqlite_fts4.py::test_fixture_sets_up_database PASSED          [ 10%]
[   13s] tests/test_sqlite_fts4.py::test_decode_matchinfo[dog-expected0] FAILED   [ 20%]
[   13s] tests/test_sqlite_fts4.py::test_decode_matchinfo[cat-expected1] FAILED   [ 30%]
[   13s] tests/test_sqlite_fts4.py::test_underlying_decode_matchinfo[\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00-expected0] PASSED [ 40%]
[   13s] tests/test_sqlite_fts4.py::test_rank_bm25 FAILED                         [ 50%]
[   13s] tests/test_sqlite_fts4.py::test_rank_bm25_no_match PASSED                [ 60%]
[   13s] tests/test_sqlite_fts4.py::test_annotate_matchinfo FAILED                [ 70%]
[   13s] tests/test_sqlite_fts4.py::test_annotate_matchinfo_empty PASSED          [ 80%]
[   13s] tests/test_sqlite_fts4.py::test_annotate_matchinfo_b FAILED              [ 90%]
[   13s] tests/test_sqlite_fts4.py::test_annotate_matchinfo_y FAILED              [100%]
[   13s] 
[   13s] =================================== FAILURES ===================================
[   13s] _____________________ test_decode_matchinfo[dog-expected0] _____________________
[   13s] 
[   13s] conn = <sqlite3.Connection object at 0x3ff85258e40>, search = 'dog'
[   13s] expected = [1, 2, 1, 1, 1, 2, ...]
[   13s] 
[   13s]     @pytest.mark.parametrize(
[   13s]         "search,expected",
[   13s]         [
[   13s]             ("dog", [1, 2, 1, 1, 1, 2, 4, 2, 5, 4, 5, 5, 5]),
[   13s]             ("cat", [1, 2, 1, 1, 1, 2, 3, 2, 5, 4, 5, 5, 5]),
[   13s]         ],
[   13s]     )
[   13s]     def test_decode_matchinfo(conn, search, expected):
[   13s]         r = conn.execute(
[   13s]             """
[   13s]             select decode_matchinfo(matchinfo(search, 'pcxnal'))
[   13s]             from search where search match ?
[   13s]         """,
[   13s]             [search],
[   13s]         ).fetchone()[0]
[   13s] >       assert expected == json.loads(r)
[   13s] E       AssertionError: assert [1, 2, 1, 1, 1, 2, ...] == [16777216, 33...33554432, ...]
[   13s] E         At index 0 diff: 1 != 16777216
[   13s] E         Full diff:
[   13s] E           [
[   13s] E         -  16777216,
[   13s] E         -  33554432,
[   13s] E         -  16777216,
[   13s] E         -  16777216,...
[   13s] E         
[   13s] E         ...Full output truncated (24 lines hidden), use '-vv' to show
[   13s] 
[   13s] tests/test_sqlite_fts4.py:54: AssertionError
[   13s] _____________________ test_decode_matchinfo[cat-expected1] _____________________
[   13s] 
[   13s] conn = <sqlite3.Connection object at 0x3ff850643f0>, search = 'cat'
[   13s] expected = [1, 2, 1, 1, 1, 2, ...]
[   13s] 
[   13s]     @pytest.mark.parametrize(
[   13s]         "search,expected",
[   13s]         [
[   13s]             ("dog", [1, 2, 1, 1, 1, 2, 4, 2, 5, 4, 5, 5, 5]),
[   13s]             ("cat", [1, 2, 1, 1, 1, 2, 3, 2, 5, 4, 5, 5, 5]),
[   13s]         ],
[   13s]     )
[   13s]     def test_decode_matchinfo(conn, search, expected):
[   13s]         r = conn.execute(
[   13s]             """
[   13s]             select decode_matchinfo(matchinfo(search, 'pcxnal'))
[   13s]             from search where search match ?
[   13s]         """,
[   13s]             [search],
[   13s]         ).fetchone()[0]
[   13s] >       assert expected == json.loads(r)
[   13s] E       AssertionError: assert [1, 2, 1, 1, 1, 2, ...] == [16777216, 33...33554432, ...]
[   13s] E         At index 0 diff: 1 != 16777216
[   13s] E         Full diff:
[   13s] E           [
[   13s] E         -  16777216,
[   13s] E         -  33554432,
[   13s] E         -  16777216,
[   13s] E         -  16777216,...
[   13s] E         
[   13s] E         ...Full output truncated (24 lines hidden), use '-vv' to show
[   13s] 
[   13s] tests/test_sqlite_fts4.py:54: AssertionError
[   13s] ________________________________ test_rank_bm25 ________________________________
[   13s] 
[   13s] conn = <sqlite3.Connection object at 0x3ff85258e40>
[   13s] 
[   13s]     def test_rank_bm25(conn):
[   13s] >       results = conn.execute(
[   13s]             """
[   13s]             select c0, c1, rank_bm25(matchinfo(search, 'pcnalx')) as bm25
[   13s]             from search where search match ?
[   13s]         """,
[   13s]             ["dog"],
[   13s]         ).fetchall()
[   13s] E       sqlite3.OperationalError: user-defined function raised exception
[   13s] 
[   13s] tests/test_sqlite_fts4.py:71: OperationalError
[   13s] ----------------------------- Captured stderr call -----------------------------
[   13s] Traceback (most recent call last):
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 21, in wrapper
[   13s]     return fn(*args, **kwargs)
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 225, in rank_bm25
[   13s]     match_info = _annotate_matchinfo(raw_match_info, "pcnalx")
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 160, in _annotate_matchinfo
[   13s]     value, idx = _next()
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 58, in _next
[   13s]     value = matchinfo[matchinfo_index]
[   13s] IndexError: list index out of range
[   13s] ___________________________ test_annotate_matchinfo ____________________________
[   13s] 
[   13s] conn = <sqlite3.Connection object at 0x3ff850644e0>
[   13s] 
[   13s]     def test_annotate_matchinfo(conn):
[   13s] >       r = conn.execute(
[   13s]             """
[   13s]             select annotate_matchinfo(matchinfo(search, 'pcxnals'), 'pcxnals')
[   13s]             from search where search match ?
[   13s]         """,
[   13s]             ["dog"],
[   13s]         ).fetchone()[0]
[   13s] E       sqlite3.OperationalError: user-defined function raised exception
[   13s] 
[   13s] tests/test_sqlite_fts4.py:95: OperationalError
[   13s] ----------------------------- Captured stderr call -----------------------------
[   13s] Traceback (most recent call last):
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 21, in wrapper
[   13s]     return fn(*args, **kwargs)
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 44, in annotate_matchinfo
[   13s]     return json.dumps(_annotate_matchinfo(buf, format_string), indent=2)
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 91, in _annotate_matchinfo
[   13s]     hits_this_column_all_rows, idx2 = _next()
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 58, in _next
[   13s]     value = matchinfo[matchinfo_index]
[   13s] IndexError: list index out of range
[   13s] __________________________ test_annotate_matchinfo_b ___________________________
[   13s] 
[   13s] conn = <sqlite3.Connection object at 0x3ff850645d0>
[   13s] 
[   13s]     @pytest.mark.skipif(
[   13s]         sqlite_version < (3, 8, 11), reason="matchinfo 'b' was added in SQLite 3.8.11"
[   13s]     )
[   13s]     def test_annotate_matchinfo_b(conn):
[   13s] >       r = conn.execute(
[   13s]             """
[   13s]             select annotate_matchinfo(matchinfo(search, 'pcb'), 'pcb')
[   13s]             from search where search match ?
[   13s]         """,
[   13s]             ["something ferret"],
[   13s]         ).fetchone()[0]
[   13s] E       sqlite3.OperationalError: user-defined function raised exception
[   13s] 
[   13s] tests/test_sqlite_fts4.py:174: OperationalError
[   13s] ----------------------------- Captured stderr call -----------------------------
[   13s] Traceback (most recent call last):
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 21, in wrapper
[   13s]     return fn(*args, **kwargs)
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 44, in annotate_matchinfo
[   13s]     return json.dumps(_annotate_matchinfo(buf, format_string), indent=2)
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 132, in _annotate_matchinfo
[   13s]     v = _next()[0]
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 58, in _next
[   13s]     value = matchinfo[matchinfo_index]
[   13s] IndexError: list index out of range
[   13s] __________________________ test_annotate_matchinfo_y ___________________________
[   13s] 
[   13s] conn = <sqlite3.Connection object at 0x3ff850646c0>
[   13s] 
[   13s]     @pytest.mark.skipif(
[   13s]         sqlite_version < (3, 8, 10), reason="matchinfo 'y' was added in SQLite 3.8.10"
[   13s]     )
[   13s]     def test_annotate_matchinfo_y(conn):
[   13s] >       r = conn.execute(
[   13s]             """
[   13s]             select annotate_matchinfo(matchinfo(search, 'pcy'), 'pcy')
[   13s]             from search where search match ?
[   13s]         """,
[   13s]             ["something ferret"],
[   13s]         ).fetchone()[0]
[   13s] E       sqlite3.OperationalError: user-defined function raised exception
[   13s] 
[   13s] tests/test_sqlite_fts4.py:196: OperationalError
[   13s] ----------------------------- Captured stderr call -----------------------------
[   13s] Traceback (most recent call last):
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 21, in wrapper
[   13s]     return fn(*args, **kwargs)
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 44, in annotate_matchinfo
[   13s]     return json.dumps(_annotate_matchinfo(buf, format_string), indent=2)
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 113, in _annotate_matchinfo
[   13s]     hits_for_phrase_in_col, idx = _next()
[   13s]   File "/home/abuild/rpmbuild/BUILD/sqlite-fts4-1.0.2/sqlite_fts4/__init__.py", line 58, in _next
[   13s]     value = matchinfo[matchinfo_index]
[   13s] IndexError: list index out of range
```
You can receive test systems based on s390x to reproduce (as part of Github or sponsored by IBM):
[120 days access for building](https://developer.ibm.com/articles/get-started-with-ibm-linuxone) or [long term access for CI/CD](https://www.ibm.com/community/z/open-source/virtual-machines-request/)

**Comment by skriesch** [comment]
It seems, that the numbers have been forwarded with the patch.

**Comment by simonw** [comment]
Trying to figure out if I can emulate s390x in GitHub Actions.

Found this in GitHub code search: https://github.com/ntop/nDPI/blob/86a3e4c8c331773156283d365aa6a9b103ca44ff/.github/workflows/build.yml#L491-L505

**Comment by simonw** [comment]
Annoying, I'm getting this error from that:

> standard_init_linux.go:228: exec user process caused: exec format error

e.g. on https://github.com/simonw/playing-with-actions-2/runs/7587633481?check_suite_focus=true

https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error suggests that this error happens when you build an image for the wrong architecture.

**Comment by simonw** [comment]
Maybe I also need this step:

https://github.com/ntop/nDPI/blob/86a3e4c8c331773156283d365aa6a9b103ca44ff/.github/workflows/build.yml#L280-L283

```
      - name: Setup multiarch/qemu-user-static
        if: startsWith(matrix.os, 'ubuntu') && !startsWith(matrix.arch, 'x86_64')
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
```

**Comment by simonw** [comment]
OK, that looks promising! Output from that test workflow: https://github.com/simonw/playing-with-actions-2/runs/7587692324?check_suite_focus=true
```
Linux 5f5f8b03f079 5.15.0-1014-azure #17~20.04.1-Ubuntu SMP Thu Jun 23 20:01:51 UTC 2022 s390x s390x s390x GNU/Linux
Byte Order:          Big Endian
[...]
Python 2.7.17
Python 3.6.9
big
```
So I can run Python code on an emulated big-endian system using GitHub Actions with Docker and QEMU.

Here's the workflow I used there:

```yaml
name: QEMU to run s390x-bionic

on:
  push:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: Setup multiarch/qemu-user-static
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - name: Display qemu specified architecture (s390x - big endian)
      uses: docker://multiarch/ubuntu-core:s390x-bionic
      with:
        args: >
          bash -c
          "uname -a &&
          lscpu | grep Endian
          "
    - name: Configure and compile using qemu for the specified architecture (s390x - big endian)
      uses: docker://multiarch/ubuntu-core:s390x-bionic
      with:
        args: >
          bash -c
          "apt-get -y update &&
          apt-get -y install python python3 &&
          python --version &&
          python3 --version &&
          python -c 'import sys; print(sys.byteorder)'
          "
```

**Comment by simonw** [comment]
I'm going to try using `s390x-focal` to see if I get a more recent Python than 3.6: https://hub.docker.com/r/multiarch/ubuntu-core/tags?page=1&name=s390x

**Comment by simonw** [comment]
New simplified workflow:
```yaml
name: QEMU to run s390x-bionic

on:
  push:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: Setup multiarch/qemu-user-static
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - name: Display qemu specified architecture (s390x - big endian)
      uses: docker://multiarch/ubuntu-core:s390x-bionic
      with:
        args: >
          bash -c
          "uname -a &&
          lscpu | grep Endian
          "
    - name: Configure and compile using qemu for the specified architecture (s390x - big endian)
      uses: docker://multiarch/ubuntu-core:s390x-bionic
      with:
        args: >
          bash -c
          "apt-get -y update &&
          apt-get -y install python python3 &&
          python --version &&
          python3 --version &&
          python -c 'import sys; print(sys.byteorder)'
          "
```
This gives Python 3.8:

```
Python 2.7.18
Python 3.8.10
big
```

**Comment by simonw** [comment]
That did it! I got the same test failures you reported, running in GitHub Actions: https://github.com/simonw/playing-with-actions-2/runs/7587833777?check_suite_focus=true

**Comment by simonw** [comment]
On my Mac running Docker Desktop this works too:

    docker run --rm --privileged multiarch/qemu-user-static:register --reset
    docker run -it multiarch/ubuntu-core:s390x-focal /bin/bash

That dropped me into a shell on an emulated machine. I could then run this:

    apt-get update && apt-get -y install python3 git
    # ...
    python3 -c 'import sys; print(sys.byteorder)'
    # Output: big

I had to run `docker system prune --all --force --volumes` first as a workaround for an error I was seeing running `apt-get`: "At least one invalid signature was encountered." - tip here: https://stackoverflow.com/questions/59139453/repository-is-not-signed-in-docker-build#comment126967448_62472785

**Comment by simonw** [comment]
I think my original interpretation of this bug may have been incorrect.

I thought that SQLite would always return `matchinfo()` output in little-endian byte order.

But I've got the same code running on a little-endian and a big-endian machine now and on the big-endian machine:

```
(Pdb) bb = conn.execute("select matchinfo(search, 'pcxnal') from search where search match ?", [search]).fetchone()[0]
(Pdb) bb
b'\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x02\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00\x05'
(Pdb) decode_matchinfo(bb)
(16777216, 33554432, 16777216, 16777216, 16777216, 33554432, 67108864, 33554432, 83886080, 67108864, 83886080, 83886080, 83886080)
```
Where-as on the little-endian machine:
```
(Pdb) bb = conn.execute("select matchinfo(search, 'pcxnal') from search where search match ?", [search]).fetchone()[0]
(Pdb) 
(Pdb) bb
b'\x01\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00'
(Pdb) decode_matchinfo(bb)
(1, 2, 1, 1, 1, 2, 3, 2, 5, 4, 5, 5, 5)
```
And when I compare the `bb` byte strings they are NOT the same!

```
b'\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x02\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00\x05'
b'\x01\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00'
```
So I looked at the SQLite docs and: https://www.sqlite.org/fts3.html#matchinfo

> The matchinfo function returns a blob value. If it is used within a query that does not use the full-text index (a "query by rowid" or "linear scan"), then the blob is zero bytes in size. Otherwise, the blob consists of zero or more 32-bit unsigned integers in machine byte-order.

But if that's in "machine byte-order" how come my original code didn't work correctly?

**Comment by simonw** [comment]
I figured it out!

The original failing test was this one: https://github.com/simonw/sqlite-fts4/blob/01727208d9133f1b9053add63953c9be2a592737/tests/test_sqlite_fts4.py#L57-L67

That's hard-coding in the little-endian input - which means the test fails on big-endian machines.

But the actual feature works correctly, because SQLite returns data in the expected endian-ness.

**Comment by simonw** [comment]
On little-endian:
```
(Pdb) import struct
(Pdb) struct.pack('IIII', 1, 2, 2, 2)
b'\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00'
```
On big-endian:
```
>>> import struct
>>> struct.pack('IIII', 1, 2, 2, 2)
b'\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02'
```
I'm going to switch to using `@IIII` for my format string - `@` means  byte order native, size native, alignment native according to https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment - it's also what Peewee uses here: https://github.com/coleifer/peewee/blob/0f1a49202b72b18074032efa56e42d4aeef95cce/playhouse/sqlite_ext.py#L1195

**Comment by simonw** [comment]
OK, the tests now pass on my laptop AND on my emulated s390x.

**Comment by simonw** [comment]
I've pushed release 1.0.3 with this new, improved fix. Leaving this issue open until you can confirm that it fixes the tests for you!

**Comment by simonw** [comment]
New TIL: https://til.simonwillison.net/docker/emulate-s390x-with-qemu

**Comment by skriesch** [comment]
Thank you! Our s390x and PPC64 builds are succeeding now. :)
Your blog articles are really interesting! If you are interested for more knowledge regarding mainframe emulations in qemu, I can recommend you to read my Bachelor Thesis. I wrote about containerized qemu emulations (for the goal of usage on community projects on Github) and that was supported by IBM:[Bachelor Thesis]( https://github.com/skriesch/BachelorThesis/blob/master/thesis.pdf)

There is also described, how qemu-s390x and binfmt_misc are working.

**Comment by simonw** [comment]
Your thesis looks like exactly what I needed to help fill in the gaps in my knowledge, thank you very much!
