### ISSUE TITLE
Live demo is broken

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-fts4#7]
https://datasette-sqlite-fts4.datasette.io/ says: "Error 500, file is not a database" on every page.

**Comment by simonw** [comment]
From the logs:

`ERROR: conn=<pysqlite3.dbapi2.Connection object at 0x7f76d861f130>, sql = 'PRAGMA schema_version', params = None: file is not a databaseTraceback (most recent call last):File "/var/task/datasette/app.py", line 1254, in route_pathresponse = await view(request, send)File "/var/task/datasette/views/base.py", line 134, in viewreturn await self.dispatch_request(request)File "/var/task/datasette/views/base.py", line 89, in dispatch_requestawait self.ds.refresh_schemas()File "/var/task/datasette/app.py", line 350, in refresh_schemasawait self._refresh_schemas()File "/var/task/datasette/app.py", line 365, in _refresh_schemasschema_version = (await db.execute("PRAGMA schema_version")).first()[0]File "/var/task/datasette/database.py", line 242, in executeresults = await self.execute_fn(sql_operation_in_thread)File "/var/task/datasette/database.py", line 188, in execute_fnreturn await asyncio.get_event_loop().run_in_executor(File "/var/lang/lib/python3.9/concurrent/futures/thread.py", line 58, in runresult = self.fn(*self.args, **self.kwargs)File "/var/task/datasette/database.py", line 186, in in_threadreturn fn(conn)File "/var/task/datasette/database.py", line 212, in sql_operation_in_threadcursor.execute(sql, params if params is not None else {})pysqlite3.dbapi2.DatabaseError: file is not a database`

**Comment by simonw** [comment]
Here's the problem: https://github.com/simonw/sqlite-fts4/blob/3ce72b5e954cc8a10b58b5ac94daf2c0689da63b/.github/workflows/publish.yml#L62-L71

It's downloading a file from https://24ways-fts4-db.now.sh/ which doesn't exist any more.

**Comment by simonw** [comment]
Uploaded a fresh copy of that DB to https://static.simonwillison.net/static/2022/24ways-fts4.db

**Comment by simonw** [comment]
I think `curl --fail` would at least cause that workflow to fail if `curl` fails.

**Comment by simonw** [comment]
Huh, `curl --fail` did not do what I expected here - I thought the workflow would stop with an error:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/9599/181584262-15c6dc56-7eec-47bc-87c4-e5c82da76b18.png">

**Comment by simonw** [comment]
Here's why - it's serving a redirect:
```
/tmp % curl --fail --silent -o 24ways-fts4.db https://24ways-fts4-db.now.sh
/tmp % ls -lah 24ways-fts4.db 
-rw-r--r--  1 simon  wheel    56B Jul 28 09:00 24ways-fts4.db
/tmp % open 24ways-fts4.db 
/tmp % cat 24ways-fts4.db 
Redirecting to https://24ways-fts4-db.vercel.app/ (308)
```

**Comment by simonw** [comment]
That fixed it.
